- name: Roboshop project setup 
  hosts: "{{COMPONENT}}"
  become: yes  # Privileges escalation 
  roles:
    - "{{COMPONENT}}"
    # - mongodb 
  
- name: Configure Roboshop Project 
  hosts: "{{component}}"
  become: yes
  roles:
    -  "{{component}}"