- name: Coping Logstash Config file 
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/rsyslog.d/conf.d/logstash.conf
  
- name: Restarting logstash 
  ansible.builtin.systemd:
    name: logstash    
    state: restarted

# Whenever you restart a logstash, it will lot of time to come up and validation part that logstash is up is it's port number 
# 5044 should be in the listening state. So, this playbook has to wait till that port 5044 comes up and once that comes up, then only
# we can say that this task is completed. If not, logstash is having issue.

- name: Wait for logstash to come in to listening state
  ansible.builtin.wait_for:
    port: 5044
    delay: 10